### ISSUE TITLE
Hide TeamScale Findings Tab in PR

### ISSUE THREAD

**Issue by SDohle** [cqse/Teamscale-AzureDevOps-Extension#19]
Hi,

it would be great if the Teamscale Findings Tab would **not** be displayed in Pullrequests if the Extension is **not** configured for a Team project.

We have projects using Teamscale and projects not using Teamscale inside the same Collection. So it would be nice if all the Teamscale UI stuff would be only displayed if configured for the specific project. Another solution would be a checkbox option for the PR integration like it is already there for the work items.

Best regards
Steffen

**Comment by rottkit** [comment]
Hi Steffen,

unfortunately the extensibility of Azure DevOps is not flexible enough to show the "Findings" tab only for those projects that have set up a Teamscale connection.
It is also not possible to do this via a checkbox in the project configuration as the endpoint (Tab in the PR view) is defined and rendered in an earlier stage in which this information is neither present nor does the possibility exists to show the tab conditionally.

Best,
Jakob
